### ISSUE TITLE
Cann't use (require ...) in source block

### ISSUE THREAD

**Issue by zhangshenhua** [hasu/emacs-ob-racket#12]
![图片](https://github.com/user-attachments/assets/4bc04e28-e1ee-49ba-95ab-2bcf9de81e6c)

**Comment by hasu** [comment]
That behavior looks correct to me, assuming that the `:results` 
collection mode was `value` in this case, which according to Org 
documentation means that "Org gets the value by wrapping the code in a 
function definition in the language of the source block."

By default, ob-racket does something like that by wrapping the code in a 
`let`, and the last body form should then be an expression that gives 
the value of the block. Other expressions and internal definitions may 
also be included in the body sequence, but not forms like `require` that 
are only allowed in "module level or top level."

Therefore the reported syntax error is due to a property of the language 
(e.g., the Ruby language does allow using `require` within a function 
body), and not of the Org Babel language support implementation.

In ob-racket there is support for a custom `:require` header argument 
that you may use instead of a `require` form within the code of the block:
#+begin_src racket :results value :require racket/generator
   (define g (sequence->generator (in-naturals)))
   (g)
   (g)
#+end_src

#+RESULTS:
: 1

Or, with `:results output` the code of the block will be at the module 
level:
#+begin_src racket :results output
   (require racket/generator)
   (define g (sequence->generator (in-naturals)))
   (g)
   (g)
#+end_src

#+RESULTS:
: 0
: 1

**Comment by ZelphirKaltstahl** [comment]
@hasu This let-wrapping seems suspicious to me, because it makes some things impossible. What if you `(define ...)` a variable? This let wrapping, that implicitly and invisibly happens, changes the meaning of code in code blocks. A similar let wrapping caused problems with `var` header arguments for `scheme` blocks. For example:

```
Welcome to Racket v8.13 [cs].
> (let ((a 1))
    (define b 2)
    3)
3
> b
b: undefined;
 cannot reference an identifier before its definition
  in module: top-level
 [,bt for context]
> 
```

Since the code is wrapped in a `let` it becomes wrong, while it usually would be perfectly OK.

Similar issue existed with `ob-scheme` btw. If you want, read the messages in this thread: https://lists.gnu.org/archive/html/emacs-orgmode/2023-03/msg00087.html

**Comment by hasu** [comment]
Thank you for the pointer. I've taken a look at that discussion now.

I agree that it would be inconsistent to do the `let` wrapping only when 
there are `var` header arguments for a block, and ob-racket doesn't work 
that way, and as it is it doesn't even use a `let` for defining the 
`var`iables.

Rather, for the `:results value` case the wrapping is done to ensure 
that only the value of a block gets printed, and not the results of any 
prior expressions. In the Org manual it says that "when using ‘:results 
value’, code should execute like a function and return a value." The 
wrapping makes it so, because (let () body...+) is equivalent to 
((lambda () body...+)), and so the body forms of the block get "executed 
like a function," and any variables defined by them are also local to 
the function.

So although the meaning of the code changes I'd say the change isn't 
particularly "suspicious" since it's as documented.

The example you give wouldn't work anyway, since this ob-racket 
evaluates each code block with a separate racket invocation, and so the 
`define`d variables of one block can never be visible to the next. I 
assume that in :session mode things should work different, with 
top-level definitions in code blocks kept at the top level and kept 
defined for later evaluations, but I haven't looked into adding support 
for that.

**Comment by ZelphirKaltstahl** [comment]
I think for  `:results value` it makes sense to treat a block like a function with return value.

I read your comment and was wondering: "But what about when I write `(define ...)` in a block!?? That should surely be available in other blocks, which include this block." Then I read the last part of your comment:

> I assume that in :session mode things should work different, with
top-level definitions in code blocks kept at the top level and kept
defined for later evaluations, but I haven't looked into adding support
for that.

Yep, I think so too, that should definitely work differently. Otherwise the usefulness is kind of limited, preventing any top level scope things to be "prepared" in one block and then included into another as "necessary preparation code", which would limit the things one can do with org mode literate programming in Racket.

Not only `define` is important at top level though. Also `require` is important. Imagine having to repeat all imports in every source block, because they cannot be effectively included.
