### ISSUE TITLE
Code of certain pattern can not execute correctly

### ISSUE THREAD

**Issue by drcxd** [hasu/emacs-ob-racket#13]
Here is the source code block in Emacs:

```
#+begin_src racket :lang sicp
(define (fibgen a b) (cons-stream a (fibgen b (+ a b))))
(define fibs (fibgen 0 1))
fibs
#+end_src
```

`org-babel-expand-src-block` gives the following output:

```
#lang racket

(write (let ()

(define (fibgen a b) (cons-stream a (fibgen b (+ a b))))
(define fibs (fibgen 0 1))
fibs))
```

Execute this piece of code yields the following error:

```
: fibgen: undefined;
:  cannot use before initialization
:   context...:
:    c:\Users\Administrator\AppData\Local\Temp\babel-gE7w5t\org-babel-BEF6AJ.rkt:3:0
:    body of "c:\Users\Administrator\AppData\Local\Temp\babel-gE7w5t\org-babel-BEF6AJ.rkt"
```

Copy and paste the code to DrRacket yields the same error.

However, removing the `(write (let` part gives code that can be correctly executed:

```
#lang sicp

(define (fibgen a b) (cons-stream a (fibgen b (+ a b))))
(define fibs (fibgen 0 1))
fibs
```

DrRacket outputs `(0 . #<promise>)` for the final expression.

Why `(write (let` is necesssary? Is there any way to avoid such problem?

**Comment by hasu** [comment]
So the particular piece of code does evaluate without error at the sicp 
module level, and it also produces a result in racket, even with the 
implicit (let () ....) wrapping:

#+begin_src racket :results value :require "(only-in sicp cons-stream)"
   (define (fibgen a b) (cons-stream a (fibgen b (+ a b))))
   (define fibs (fibgen 0 1))
   fibs
#+end_src

#+RESULTS:
: {0 . #<promise>}

The difference between racket and sicp would appear to be the way in 
which the local `define` forms get transformed to more primitive binding 
forms. One solution then would be to transform the code yourself to be 
more explicit about the desired evaluation order:

#+begin_src racket :lang sicp :results value
   (letrec ((fibgen (lambda (a b) (cons-stream a (fibgen b (+ a b))))))
     (let ((fibs (fibgen 0 1)))
       fibs))
#+end_src

#+RESULTS:
: (0 . #<promise>)

The assumption made by ob-racket is that in :results value mode we can 
take the contents of a code block and wrap it in a (let () ....) form to 
get an expression that gives a value for the block, which can then be 
further processed by `write`ing it out, or in some cases printing it out 
as an Emacs Lisp datum.

It turns out this assumption doesn't hold for your sicp code sample 
since evaluation of the resulting expression produces an error rather 
than a result. You can avoid that kind of incompatibility by instead 
using :results output mode, in which no value printing (write (let 
....)) expression gets constructed:

#+begin_src racket :lang sicp :results output
   (define (fibgen a b) (cons-stream a (fibgen b (+ a b))))
   (define fibs (fibgen 0 1))
   fibs
#+end_src

#+RESULTS:
: (0 . #<promise>)
